### ISSUE TITLE
Tutorial on Chunking?

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/MED-core-recipes#14]
Maybe something for you @dougiesquire ?

I was thinking of something high level progressively going in details.
Using examples from COSIMA....

**Comment by rbeucher** [comment]
That sounds promising.

**Comment by rbeucher** [comment]
Hey guys, I think it would be good to have that as part of general "how-tos" in the MED CORE Recipes.
What do you think?

**Comment by dougiesquire** [comment]
Somewhat relevant, I've included a brief section on chunking in the ACCESS-NRI Intake catalog documentation: https://access-nri-intake-catalog.readthedocs.io/en/latest/usage/chunking.html

Most of what's included there is general advice not specific to the catalog
