### ISSUE TITLE
xarray memory usage with multi-variable atmospheric data

### ISSUE THREAD

**Issue by MartinDix** [ACCESS-NRI/MED-core-recipes#2]
https://github.com/MartinDix/notebooks/blob/master/xarray_memory_usage.ipynb
shows some strange behaviour of xarray with the COSIMA DB.

Processing 10 years of ocean data (1440x1080 grid) takes much less time and memory than 10 years of atmospheric data (192x144 grid).

The ocean data is in single variable files (6 months in each) while the atmospheric data is in monthly multiple variable files. The reported memory usage for the atmospheric data is ~ 100 times what the variable should actually use.

Trying to load a 100 years brings it to a grinding halt.

**Comment by MartinDix** [comment]
Comment from @kieranricardo 

But something weird is happening where the first time open_dataset is called to open a file it uses much more memory than the second time.

e.g. if in Martin's notebook you do:

```
def _preprocess(d):
    return d['fld_s03i236']
ncfiles = cc.querying._ncfiles_for_variable(
        expt,
        'fld_s03i236',
        session,
        end_time='0010-12-31',
)
ncfiles = list(str(f.NCFile.ncfile_path) for f in ncfiles)
```

and then have two cells that do:
```
%%memit 
out = _preprocess(xr.open_dataset(ncfiles[0]))
```
The first run will use 10x more memory. And the second run uses a similar amount of memory to netCDF4

Actually xarray only uses double the memory of:
```
import netCDF4 as nc
%%memit 
ds = nc.Dataset(ncfiles[0])
arr = ds['fld_s03i236'][:]
```

So maybe this weirdness lies with netCDF4 - but you'd definitely hope for things to be better

**Comment by MartinDix** [comment]
https://github.com/MartinDix/notebooks/blob/master/netCDF4_memory_usage.ipynb

Reading with netCDF4 and keeping files open (which presumably xarray does)
```
alist = []
for f in ncfiles:
    ds = nc.Dataset(f)
    arr = ds['fld_s03i236'][:]
    alist.append(arr)
```
takes ~ 550 MB, about 1/3 of what xarray uses but still strange.

Using single variable files takes 47 MB (c..f. about 13 MB for the data itself)

Using multi-variable files with the grid reduced to 1x1 takes 24 MB

There are about 220 variables in the files, so if each had a separate copy of the lat, lon and bounds arrays this would be about 2 MB per file. If true, this would go some way to explaining the memory usage, but I can't see why these coordinate arrays would exist in the simple netCDF4 interface. Even stranger, xarray with the 1x1 grid files takes the same amount of memory as the full grid files!

**Comment by kieranricardo** [comment]
bizarre! 

@MartinDix how large are the 1x1 grid files? Maybe the memory usage is due to loading the metadata

**Comment by kieranricardo** [comment]
and maybe the extra memory usage of `xarray` vs `netcdf` is due to decoding the CF convention variables. Maybe try

`
%%memit 
ds = nc.Dataset(ncfiles[0], decode_cf=False, decode_coords=False, decode_times=False, decode_timedelta=False)
arr = ds['fld_s03i236'][:]
`

**Comment by MartinDix** [comment]
`-rw-r----- 1 mrd599 tm70 1567525 Sep 15 16:07 /g/data/tm70/mrd599/cj877_1x1/cj877a.pm000101_mon.nc`

Interesting idea about the metadata. I'll set up a version where most of it is removed.

**Comment by kieranricardo** [comment]
Some new timing:

- `ds = xr.open_dataset(ncfiles[0]); arr = ds['fld_s03i236'][:]` takes for 44MiB
- `ds = xr.open_dataset(ncfiles[0], decode_cf=False, decode_coords=False, decode_times=False, decode_timedelta=False); arr = ds['fld_s03i236'][:]` takes for 27.61MiB
- `ds = nc.Dataset(ncfiles[0]); arr = ds['fld_s03i236'][:]` takes for 14.37MiB

Turning off the decoding seem to half the memory usage of xarray, but it's still double that of `NetCDF4`

**Comment by MartinDix** [comment]
The atmospheric netCDF files are netCDF4. Converting to netCDF4-classi makes no difference (`/g/data/tm70/mrd599/cj877_nc4_classic`), but with netcdf3 ((`/g/data/tm70/mrd599/cj877_nc3`) memory usage for 10 years with netCDF4 python is 25 MB and with xarray 88 MB.

A fortran program that keeps the files open takes 1350 MB with netCDF4 or netCDF4-classic and still takes 1015 MB with netCDF3 so doesn't see the same benefit for some reason.

**Comment by dougiesquire** [comment]
I also tried to take a look at this using the files Martin has in `/g/data/tm70/mrd599/cj877_nc4_classic`. I didn't make much progress, but curiously I did notice that just accessing the array data or the attributes (via `.data` and `.attr`) doesn't result in memory issues, whereas accessing the coordinates does. For example, for a single variable (`var = "fld_s03i236"`) in @MartinDix's `/g/data/tm70/mrd599/cj877_nc4_classic` files:

<img width="435" alt="Screen Shot 2022-10-13 at 8 47 05 am" src="https://user-images.githubusercontent.com/42455466/195454356-ae08ebec-9622-466a-b2d1-e4302871c4fc.png">

<img width="433" alt="Screen Shot 2022-10-13 at 8 47 23 am" src="https://user-images.githubusercontent.com/42455466/195454291-f7c7ee2f-4429-4cef-aee8-33e383be7275.png">

I also note that using `engine="h5netcdf"` reduces the memory footprint, but makes the opening take an unreasonably long time.

**Comment by aidanheerdegen** [comment]
This long running issue has some useful approaches for isolating the cause of slow multi-file reads, and some suggestions to address this

https://github.com/pydata/xarray/issues/1385

Including consulting the latest docs

https://docs.xarray.dev/en/stable/user-guide/io.html#reading-multi-file-datasets

Looking through what has been tried so far, I would suggest a `preprocess` that has `decode_cf=False`, selects out a single variable, and *then* does the `decode_cf` step.

**Comment by dougiesquire** [comment]
Thanks @aidanheerdegen . I *think* I tried this early on in the list of many things I tried yesterday without much luck, but will confirm when I'm back at a computer.

**Comment by dougiesquire** [comment]
I'm not sure we have an issue of *slow* reads, rather the issue is that the reads use far more memory than expected. If you use dask and the dashboard to visualise the memory, the unmanaged component continues to grow for the duration of the operation.

Blog post on unmanaged memory (that I don't fully understand): https://coiled.io/blog/tackling-unmanaged-memory-with-dask/

**Comment by dougiesquire** [comment]
I noticed that the netcdf4 files use `filling off` whereas the netcdf3 files have `filling on` (see https://unidata.github.io/netcdf4-python/#Dataset.set_fill_on). The netcdf4 ocean files Martin points at in his original post use `filling on`. Out of desperation, I've tried recreating the atmosphere netcdf4 files with `filling on`, but this does not help reduce the memory (file are here `/g/data/tm70/ds0092/data/cj877_nc4_classic_rebuild`)

**Comment by dougiesquire** [comment]
Another curiosity:

Simply extracting a netcdf4 variable into a list seems to have memory issues, but I can explicitly extract the array/dimensions/attributes (and e.g. pack into an xarray DataArray) without the memory going crazy.

<img width="409" alt="Screenshot 2023-02-21 at 3 44 09 pm" src="https://user-images.githubusercontent.com/42455466/220249819-a6925b63-ba7e-471c-821b-20759ce09f5b.png">

**Comment by dougiesquire** [comment]
FYI, I opened an issue [here](https://github.com/Unidata/netcdf4-python/issues/1235)

**Comment by dougiesquire** [comment]
This issue also has some potentially relevant tidbits:

https://github.com/Unidata/netcdf-c/issues/489

**Comment by dougiesquire** [comment]
Note that using kerchunk with these files (avoiding the netcdf library) seems to completely resolve this issue, see [notebook here](https://github.com/ACCESS-NRI/dev_data_querying/blob/bfaa99c1d4c103ef976158059d05c3ada0caff25/cosima_intake/kerchunk_cm2_atmosphere/kerchunk_cj877.ipynb)

**Comment by aidanheerdegen** [comment]
> This issue also has some potentially relevant tidbits:
> 
> [Unidata/netcdf-c#489](https://github.com/Unidata/netcdf-c/issues/489)

This was apparently fixed over 4 years ago. Any version >= 4.6.3 should include these fixes

https://github.com/Unidata/netcdf-c/issues/489#issuecomment-449728217

but the file needs to be written by a new enough version of the library to include some hidden metadata

https://github.com/Unidata/netcdf-c/issues/489#issuecomment-449762905

https://github.com/Unidata/netcdf-c/pull/1262

**Comment by dougiesquire** [comment]
> but the file needs to be written by a new enough version of the library to include some hidden metadata

@MartinDix  created test versions of the original files (e.g. converted from netcdf4 to netcdf4-classic). These test versions also have the issue and were presumably converted using a recent version of netcdf4? I'm don't know whether the convertion would add the hidden metadata though... Worth checking

**Comment by aidanheerdegen** [comment]
> presumably converted using a recent version of netcdf4

https://www.getyarn.io/yarn-clip/584cffc0-12f0-49a4-bd94-8d66efc69356
