### ISSUE TITLE
Add Observational datasets to the COSIMA-Cookbook

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/MED-core-recipes#3]
There has been discussions about adding Observational datasets to the COSIMA-Cookbook to enable comparisons between simulations and observations.

See Here: https://github.com/COSIMA/cosima-recipes/issues/6

I propose we work on a COSIMA-data system similar to ILAMB-data.

The issue mentions WOA13 that is available on HH5 and has been re-gridded and made CF Compliant.
We could start the COSIMA-data with WOA18 and process it in a same way.

@echus

**Comment by aidanheerdegen** [comment]
WOA18 is already indexed from this directory `/g/data/ik11/observations/woa18`.

**Comment by rbeucher** [comment]
OK good. I think we also need to make sure that the processing-steps have been captured (for reproducibility)
