### ISSUE TITLE
Add CEDA Archive to the Hive

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/MED-core-recipes#54]
We should add the CEDA Archive to the Hive (Catalogue section)
https://archive.ceda.ac.uk/

**Comment by rbeucher** [comment]
@rhaegar325 do you want to have a go at this?

**Comment by rhaegar325** [comment]
Yes, sorry I working on iomb this days and did do it yet. I will do it this
afternoon.

**Comment by svenbuder** [comment]
Solved as part of merging for CEDA update on community models #328
