### ISSUE TITLE
Notebooks to be reviewed and added to the MED Core

### ISSUE THREAD

**Issue by rbeucher** [ACCESS-NRI/MED-core-recipes#69]
@markcollier from CSIRO has worked on some evaluation notebooks that would be useful do document and add to the MED Core.

Notebook that computed energy related quantities.

[https://notebooksharing.space/view/a05bc3c71e4e0cd9a7c5bb80335b5c54a851d3bc34743889781d6623feb80e44](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotebooksharing.space%2Fview%2Fa05bc3c71e4e0cd9a7c5bb80335b5c54a851d3bc34743889781d6623feb80e44&data=05%7C01%7CRomain.Beucher%40anu.edu.au%7C94d555f1b553411e32d308db54feaf88%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638197225070883372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0IWiNtdBM%2FFPRDtOSqkl8hYrr0hMiiUH%2F%2F8e5IM4pMU%3D&reserved=0)

To run this script generally takes a few days to make sure all the intermediate files are ready for each subsequent step. If it were to be on a coarser grid than 0.1 then it would be doable in a fraction of a day.

Notebook that calculates mass overturning on a basin basis as a function of depth and latitude.

It uses a cluster to do the work and writes out the data using CMOR which has its advantages.

[https://notebooksharing.space/view/fc12dca55761de6081f22058ea227f59f9c8c727b9379e3227157c7f2f4b9340](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotebooksharing.space%2Fview%2Ffc12dca55761de6081f22058ea227f59f9c8c727b9379e3227157c7f2f4b9340&data=05%7C01%7CRomain.Beucher%40anu.edu.au%7C52b4220152dc4ae94ac208db57466169%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638199732014641440%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FM6NmJdtqDd86uaOl2hqfg1A3u%2F4C%2FEmvyKJZonnq2k%3D&reserved=0)

I still plan to write a notebook for choke point transports and heat content calculations.

Notebook that calculates transports across ‘choke points’ as a function of sector and time.

[https://notebooksharing.space/view/3555c2fee958daba8787ce1f8311826b45b69c86b69b5169255e1251a32eb025](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotebooksharing.space%2Fview%2F3555c2fee958daba8787ce1f8311826b45b69c86b69b5169255e1251a32eb025&data=05%7C01%7CRomain.Beucher%40anu.edu.au%7C5f45df31c3984f38f9e608db582100a4%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638200670989117689%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=a2BPtjXd%2B9M9zVmDkIczKwjQAGWEROKaGhmqmQD0aqw%3D&reserved=0)

Notebook that generates plots of some standard indices from the Meridional Ocean Mass Transport (or CMIP6 variable msftmz) generated in a previous example

[https://notebooksharing.space/view/8f3e152f877a3081fa3db237cc807cad37c25dd062ae9d49ea1c0b6d8c3d7cc3](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotebooksharing.space%2Fview%2F8f3e152f877a3081fa3db237cc807cad37c25dd062ae9d49ea1c0b6d8c3d7cc3&data=05%7C01%7CRomain.Beucher%40anu.edu.au%7C82bcfeb991834bcdd9ff08db5b2a67d2%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638204009928569229%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=FBf5vPXwZ5EssK5EeXJ3ePAEB5vPefpCXXkDDFd2EJk%3D&reserved=0)

Notebook that calculates ocean heat content as a function of basin, depth and time.

[https://notebooksharing.space/view/f526474bf0fb090bb1abf3b6d82e5223f4a92af3526f240648f0bd0ffe12f47a](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotebooksharing.space%2Fview%2Ff526474bf0fb090bb1abf3b6d82e5223f4a92af3526f240648f0bd0ffe12f47a&data=05%7C01%7CRomain.Beucher%40anu.edu.au%7Cf3182cb64e5a412d862708db5b3295b3%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638204045038052537%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=r7Oh9yQRiovoIZdVA%2FeOUaIpFFMi4AH9ehezFu3qYec%3D&reserved=0)

@headmetal ?

**Comment by rbeucher** [comment]
Quoting @markcollier:

another notebook that calculates ocean mass transport as function of time, latitude and depth (both density and depth coordinate), relying on appropriate ty_trans inputs, and plotting them.


Would be good to sum up the contributions to compare with the global result, also to generate the submeso contributions if the inputs are available and to plot these. Also creating overturning on density coordinates from depth coordinate data would be good, and a comparison to see how accurately it works.


[https://notebooksharing.space/view/f526474bf0fb090bb1abf3b6d82e5223f4a92af3526f240648f0bd0ffe12f47a](https://aus01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fnotebooksharing.space%2Fview%2Ff526474bf0fb090bb1abf3b6d82e5223f4a92af3526f240648f0bd0ffe12f47a&data=05%7C01%7CRomain.Beucher%40anu.edu.au%7C1d76012b81df47dee24f08db5e459f58%7Ce37d725cab5c46249ae5f0533e486437%7C0%7C0%7C638207425347788693%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JyYgbqqV6rerOxkkCRLfhT6JyZbw1jV2tTJLv6ngPIo%3D&reserved=0)

**Comment by markcollier** [comment]
Hi Romain, I have a test to compare the direct global V the indirect global (summed individual basins) and they give the same result for both computations on z or rho coordinate, really just a check of whether the basin definitions are correct but worth examining.

The notebooks are being written to a directory on my account, and will continue to be developed, these can eventually be put on git or somewhere to be put into a more generalise formed (e.g. COSIMA cookbook). This last step is very difficult and beyond my time commitment. I develop notebooks as a researcher and not a computational scientist, getting them to work reliably and simply is my approach, whereas another might try for elegance or to minimise resources…

For our paper I needed to do similar computations for a range of model resolutions and experiments, it is quite tricky to get everything in place but I thought it best to focus on one experiment so as not to clutter the notebooks too much.

Cheers, M.

From: Romain Beucher ***@***.***>
Date: Monday, 29 May 2023 at 11:08 am
To: ACCESS-NRI/MED-core-recipes ***@***.***>
Cc: Collier, Mark (Environment, Aspendale) ***@***.***>, Mention ***@***.***>
Subject: Re: [ACCESS-NRI/MED-core-recipes] Notebooks to be reviewed and added to the MED Core (Issue #69)

Quoting @markcollier<https://github.com/markcollier>:

another notebook that calculates ocean mass transport as function of time, latitude and depth (both density and depth coordinate), relying on appropriate ty_trans inputs, and plotting them.

Would be good to sum up the contributions to compare with the global result, also to generate the submeso contributions if the inputs are available and to plot these. Also creating overturning on density coordinates from depth coordinate data would be good, and a comparison to see how accurately it works.

https://notebooksharing.space/view/f526474bf0fb090bb1abf3b6d82e5223f4a92af3526f240648f0bd0ffe12f47a

**Comment by rbeucher** [comment]
Hi Mark,

Thanks for your contributions. I had a quick chat with @headmetal who is part of the NRI. He is going to have a look at your notebooks and will probably have some questions.  We are working on a way to streamline those contributions into a catalog of user recipes.

Romain
